# Generated by Django 4.2.5 on 2023-09-08 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catergory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='наименование')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo1', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='фото1')),
                ('photo2', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='фото2')),
                ('photo3', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='фото3')),
                ('photo4', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='фото4')),
                ('photo5', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='фото5')),
                ('title', models.CharField(max_length=300, verbose_name='наименование')),
                ('comment', models.TextField(verbose_name='описание')),
                ('date_of_creation', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('date_of_change', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('catergory', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.catergory', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'объявление',
                'verbose_name_plural': 'объявления',
            },
        ),
    ]
