# Generated by Django 4.2.5 on 2023-09-22 03:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Catergory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='наименование')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='фото')),
                ('fields', models.JSONField(blank=True, null=True, verbose_name='список полей')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='наименование')),
            ],
            options={
                'verbose_name': 'цвет',
                'verbose_name_plural': 'цвета',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='наименование')),
            ],
            options={
                'verbose_name': 'район',
                'verbose_name_plural': 'районы',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='наименование')),
            ],
            options={
                'verbose_name': 'область',
                'verbose_name_plural': 'области',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo1', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='фото1')),
                ('photo2', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='фото2')),
                ('photo3', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='фото3')),
                ('photo4', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='фото4')),
                ('photo5', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='фото5')),
                ('title', models.CharField(max_length=300, verbose_name='наименование')),
                ('text', models.CharField(max_length=2000, verbose_name='описание')),
                ('punkt', models.CharField(blank=True, max_length=150, null=True, verbose_name='населеный пункт')),
                ('date_of_action', models.DateField(blank=True, null=True, verbose_name='дата совершения')),
                ('brand', models.CharField(blank=True, max_length=300, null=True, verbose_name='Марка / Модель')),
                ('series', models.CharField(blank=True, max_length=300, null=True, verbose_name='Серия')),
                ('number', models.CharField(blank=True, max_length=300, null=True, verbose_name='Номер')),
                ('year_of_release', models.PositiveIntegerField(blank=True, null=True, verbose_name='Год выпуска')),
                ('manufacturer', models.CharField(blank=True, max_length=300, null=True, verbose_name='Завод изготовитель / Страна')),
                ('tone', models.CharField(blank=True, max_length=150, null=True, verbose_name='оттенок')),
                ('size', models.CharField(blank=True, max_length=150, null=True, verbose_name='размер')),
                ('features', models.CharField(blank=True, max_length=300, null=True, verbose_name='особенности')),
                ('imei', models.CharField(blank=True, max_length=150, null=True, verbose_name='IMEI код')),
                ('state_number', models.CharField(blank=True, max_length=150, null=True, verbose_name='гос. номер')),
                ('date_of_creation', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('date_of_change', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='инициатор')),
                ('catergory', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.catergory', verbose_name='категория')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='main.color', verbose_name='основной цвет')),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='main.district', verbose_name='район')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='main.region', verbose_name='область')),
            ],
            options={
                'verbose_name': 'объявление',
                'verbose_name_plural': 'объявления',
            },
        ),
    ]
