# Generated by Django 4.2.5 on 2023-09-22 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_place_item_district'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catergory',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='catergory',
            new_name='category',
        ),
    ]
