# Generated by Django 4.2.5 on 2023-09-27 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_category_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('order',), 'verbose_name': 'категория', 'verbose_name_plural': 'категории'},
        ),
    ]
