# Generated by Django 4.2.5 on 2023-09-29 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_category_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='порядковый номер')),
                ('title', models.CharField(max_length=300, verbose_name='наименование')),
                ('text', models.CharField(blank=True, max_length=5000, null=True, verbose_name='описание')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='фото')),
                ('date_of_creation', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('date_of_change', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
            ],
            options={
                'verbose_name': 'новость',
                'verbose_name_plural': 'новости',
            },
        ),
    ]
