# Generated by Django 4.2.5 on 2023-10-04 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_category_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.TextField(max_length=2000, verbose_name='описание'),
        ),
    ]
